service: video-on-demand

custom:
  stage: ${opt:stage, 'dev'}
  config: file(./config/${self:custom.stage}.json)

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: ${self:custom.stage}
  region: ${${self:custom.config}:AWS_REGION}

package:
  individually: true
  exclude:
    - .git/**
    - ./config/**

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    events: 
      - http:
          path: /test/api/hello
          method: post
          cors: true
    package:
      artifact: bin/release/netcoreapp2.1/hello.zip